### ISSUE TITLE
Malformed XML viewbox

### ISSUE THREAD

**Issue by stevenbuehner** [thecreation/standard-icons#1]
Corretly it would be viewBox (with capital B). But in this repository it is "viewbox". This results in multiple errors when handling the file i.e. with svgo and even some brothers like Safari.

**Comment by thecreation** [comment]
Thanks for reporting. We copy the svg from origin repo. It may have the wrong usage. Which icon set you used having the wrong viewbox?

**Comment by stevenbuehner** [comment]
Thank you for your response. It has been quite some time, since I recognized this problem. I finally switched to another icons-repository. 

Doing a grep at the current master, it seems that the problems have been solved in the current master.

Back then (commit: 982f4f055a0f92031adba9549fd40dd5124edc76) the problem (viewbox wihtout capital "B") accured in the entypo icon-set. For example in the files: 
- /modules/entypo/icons/search.svg
- /modules/entypo/icons/signal.svg
- /modules/entypo/icons/behance.svg
